<?php
$items = [
    'icon' => 'fa fa-database',
    'label' => 'kamille',
    'items' => [
        [
            'label' => 'ek_address',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_address',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_backoffice_user',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_backoffice_user',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_cart',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_cart',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_country',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_country',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_country_lang',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_country_lang',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_currency',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_currency',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_lang',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_lang',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_product',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_product',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_product_attibute_value',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_product_attibute_value',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_product_attribute',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_product_attribute',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_product_has_product_attribute',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_product_has_product_attribute',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_product_has_video',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_product_has_video',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_product_reference',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_product_reference',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_product_reference_shop',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_product_reference_shop',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_product_reference_store',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_product_reference_store',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_role_badge',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_role_badge',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_role_group',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_role_group',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_role_group_has_role_badge',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_role_group_has_role_badge',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_role_profile',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_role_profile',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_role_profile_has_role_badge',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_role_profile_has_role_badge',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_role_profile_has_role_group',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_role_profile_has_role_group',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_shop',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_shop',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_shop_has_product',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_shop_has_product',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_shop_has_store',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_shop_has_store',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_state',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_state',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_store',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_store',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_tax',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_tax',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_tax_lang',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_tax_lang',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_tax_rule',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_tax_rule',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_timezone',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_timezone',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_user',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_user',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_user_group',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_user_group',
            'items' => NULL,
            'icon' => '',
        ],
        [
            'label' => 'ek_video',
            'link' => '/crud?type=list&prc=Ekom.kamille.ek_video',
            'items' => NULL,
            'icon' => '',
        ],
    ],
];

