routeId:
    uri: /url/pou/{pou}
    controller: Controller:method

Core_route1:
    uri: /url/pou/{pou}
    controller: Controller:method

routeId2:
    uri: /url/pou/{pou}
    params: /url/pou/{pou}
    requirements:
    controller: Controller:method
    position: 6

routeId3:
    uri: /url/pou/{pou}
    params: /url/pou/{pou}
    requirements:
    controller: Controller:method


routeId4:
    uri: /url/pou/{pou}
    params: /url/pou/{pou}
    requirements: <
        function(HttpRequest $request){
            return true;
        }
    >
    controller: Controller:method




