-- MySQL Script generated by MySQL Workbench
-- Thu Apr 27 21:17:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ek_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iso_code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iso_code` VARCHAR(64) NOT NULL,
  `label` VARCHAR(64) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_state_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_state_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`ek_country` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(64) NOT NULL,
  `city` VARCHAR(64) NOT NULL,
  `postcode` VARCHAR(12) NOT NULL,
  `address` VARCHAR(256) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `state_id` INT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_state1_idx` (`state_id` ASC),
  INDEX `fk_address_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_address_state1`
    FOREIGN KEY (`state_id`)
    REFERENCES `mydb`.`ek_state` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_address_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`ek_country` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_user_group` (
  `id` INT NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_group_id` INT NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `base_shop_id` INT NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `main_address_id` INT NOT NULL,
  `mobile` VARCHAR(24) NOT NULL,
  `phone` VARCHAR(24) NOT NULL,
  `pro` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_address1_idx` (`main_address_id` ASC),
  INDEX `fk_user_user_group1_idx` (`user_group_id` ASC),
  CONSTRAINT `fk_user_address1`
    FOREIGN KEY (`main_address_id`)
    REFERENCES `mydb`.`ek_address` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_user_group1`
    FOREIGN KEY (`user_group_id`)
    REFERENCES `mydb`.`ek_user_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_lang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `iso_code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_currency` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iso_code` VARCHAR(3) NOT NULL,
  `symbol` VARCHAR(12) NOT NULL,
  `exchange_rate` DECIMAL(20,6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_timezone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_timezone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  `lang_id` INT NULL,
  `currency_id` INT NULL,
  `timezone_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shop_lang1_idx` (`lang_id` ASC),
  INDEX `fk_shop_currency1_idx` (`currency_id` ASC),
  INDEX `fk_shop_timezone1_idx` (`timezone_id` ASC),
  CONSTRAINT `fk_shop_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_shop_currency1`
    FOREIGN KEY (`currency_id`)
    REFERENCES `mydb`.`ek_currency` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_shop_timezone1`
    FOREIGN KEY (`timezone_id`)
    REFERENCES `mydb`.`ek_timezone` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_backoffice_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_backoffice_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_backoffice_user_lang_idx` (`lang_id` ASC),
  CONSTRAINT `fk_backoffice_user_lang`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_role_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_role_profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `backoffice_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_profile_backoffice_user1_idx` (`backoffice_user_id` ASC),
  CONSTRAINT `fk_role_profile_backoffice_user1`
    FOREIGN KEY (`backoffice_user_id`)
    REFERENCES `mydb`.`ek_backoffice_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_role_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_role_badge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_role_profile_has_role_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_role_profile_has_role_badge` (
  `role_profile_id` INT NOT NULL,
  `role_badge_id` INT NOT NULL,
  PRIMARY KEY (`role_profile_id`, `role_badge_id`),
  INDEX `fk_role_profile_has_role_badge_role_badge1_idx` (`role_badge_id` ASC),
  INDEX `fk_role_profile_has_role_badge_role_profile1_idx` (`role_profile_id` ASC),
  CONSTRAINT `fk_role_profile_has_role_badge_role_profile1`
    FOREIGN KEY (`role_profile_id`)
    REFERENCES `mydb`.`ek_role_profile` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_role_profile_has_role_badge_role_badge1`
    FOREIGN KEY (`role_badge_id`)
    REFERENCES `mydb`.`ek_role_badge` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_role_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_role_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `role_group_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_group_role_group1_idx` (`role_group_id` ASC),
  CONSTRAINT `fk_role_group_role_group1`
    FOREIGN KEY (`role_group_id`)
    REFERENCES `mydb`.`ek_role_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_role_group_has_role_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_role_group_has_role_badge` (
  `role_group_id` INT NOT NULL,
  `role_badge_id` INT NOT NULL,
  PRIMARY KEY (`role_group_id`, `role_badge_id`),
  INDEX `fk_role_group_has_role_badge_role_badge1_idx` (`role_badge_id` ASC),
  INDEX `fk_role_group_has_role_badge_role_group1_idx` (`role_group_id` ASC),
  CONSTRAINT `fk_role_group_has_role_badge_role_group1`
    FOREIGN KEY (`role_group_id`)
    REFERENCES `mydb`.`ek_role_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_role_group_has_role_badge_role_badge1`
    FOREIGN KEY (`role_badge_id`)
    REFERENCES `mydb`.`ek_role_badge` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_role_profile_has_role_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_role_profile_has_role_group` (
  `role_profile_id` INT NOT NULL,
  `role_group_id` INT NOT NULL,
  PRIMARY KEY (`role_profile_id`, `role_group_id`),
  INDEX `fk_role_profile_has_role_group_role_group1_idx` (`role_group_id` ASC),
  INDEX `fk_role_profile_has_role_group_role_profile1_idx` (`role_profile_id` ASC),
  CONSTRAINT `fk_role_profile_has_role_group_role_profile1`
    FOREIGN KEY (`role_profile_id`)
    REFERENCES `mydb`.`ek_role_profile` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_role_profile_has_role_group_role_group1`
    FOREIGN KEY (`role_group_id`)
    REFERENCES `mydb`.`ek_role_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_country_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_country_lang` (
  `country_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `label` VARCHAR(64) NOT NULL,
  INDEX `fk_country_lang_country1_idx` (`country_id` ASC),
  INDEX `fk_country_lang_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_country_lang_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`ek_country` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_country_lang_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `items` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`ek_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_reference` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `natural_reference` VARCHAR(256) NOT NULL,
  `reference` VARCHAR(64) NOT NULL,
  `weight` DECIMAL(20,6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_reference_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_product_reference1_idx` (`product_reference_id` ASC),
  CONSTRAINT `fk_product_product_reference1`
    FOREIGN KEY (`product_reference_id`)
    REFERENCES `mydb`.`ek_product_reference` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_attribute` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_attribute_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_product_attribute_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_attibute_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_attibute_value` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_attibute_value_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_product_attibute_value_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_has_product_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_has_product_attribute` (
  `product_id` INT NOT NULL,
  `product_attribute_id` INT NOT NULL,
  `product_attibute_value_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `product_attribute_id`),
  INDEX `fk_product_has_product_attribute_product_attribute1_idx` (`product_attribute_id` ASC),
  INDEX `fk_product_has_product_attribute_product1_idx` (`product_id` ASC),
  INDEX `fk_product_has_product_attribute_product_attibute_value1_idx` (`product_attibute_value_id` ASC),
  CONSTRAINT `fk_product_has_product_attribute_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_has_product_attribute_product_attribute1`
    FOREIGN KEY (`product_attribute_id`)
    REFERENCES `mydb`.`ek_product_attribute` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_has_product_attribute_product_attibute_value1`
    FOREIGN KEY (`product_attibute_value_id`)
    REFERENCES `mydb`.`ek_product_attibute_value` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uri` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_has_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_has_video` (
  `product_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `video_id`),
  INDEX `fk_product_has_video_video1_idx` (`video_id` ASC),
  INDEX `fk_product_has_video_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_has_video_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_has_video_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `mydb`.`ek_video` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_reference_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_reference_shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(256) NOT NULL,
  `prix_ht` DECIMAL(20,6) NOT NULL,
  `shop_id` INT NOT NULL,
  `product_reference_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_reference_shop_shop1_idx` (`shop_id` ASC),
  INDEX `fk_product_reference_shop_product_reference1_idx` (`product_reference_id` ASC),
  CONSTRAINT `fk_product_reference_shop_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_reference_shop_product_reference1`
    FOREIGN KEY (`product_reference_id`)
    REFERENCES `mydb`.`ek_product_reference` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_reference_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_reference_store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `product_reference_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_reference_store_store1_idx` (`store_id` ASC),
  INDEX `fk_product_reference_store_product_reference1_idx` (`product_reference_id` ASC),
  CONSTRAINT `fk_product_reference_store_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `mydb`.`ek_store` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_reference_store_product_reference1`
    FOREIGN KEY (`product_reference_id`)
    REFERENCES `mydb`.`ek_product_reference` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_shop_has_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_shop_has_store` (
  `shop_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`shop_id`, `store_id`),
  INDEX `fk_shop_has_store_store1_idx` (`store_id` ASC),
  INDEX `fk_shop_has_store_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_shop_has_store_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shop_has_store_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `mydb`.`ek_store` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_shop_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_shop_has_product` (
  `shop_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`shop_id`, `product_id`),
  INDEX `fk_shop_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_shop_has_product_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_shop_has_product_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shop_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_tax_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_tax_lang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tax_lang_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_tax_lang_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_tax` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reduction` VARCHAR(24) NOT NULL,
  `tax_lang_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tax_tax_lang1_idx` (`tax_lang_id` ASC),
  CONSTRAINT `fk_tax_tax_lang1`
    FOREIGN KEY (`tax_lang_id`)
    REFERENCES `mydb`.`ek_tax_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_tax_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_tax_rule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tax_id` INT NOT NULL,
  `condition` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tax_rule_tax1_idx` (`tax_id` ASC),
  CONSTRAINT `fk_tax_rule_tax1`
    FOREIGN KEY (`tax_id`)
    REFERENCES `mydb`.`ek_tax` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_has_tax_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_has_tax_rule` (
  `product_id` INT NOT NULL,
  `tax_rule_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `tax_rule_id`),
  INDEX `fk_product_has_tax_rule_tax_rule1_idx` (`tax_rule_id` ASC),
  INDEX `fk_product_has_tax_rule_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_has_tax_rule_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_has_tax_rule_tax_rule1`
    FOREIGN KEY (`tax_rule_id`)
    REFERENCES `mydb`.`ek_tax_rule` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `shop_id` INT NOT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_shop1_idx` (`shop_id` ASC),
  INDEX `fk_category_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_category_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`ek_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_category_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_category_has_product` (
  `category_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `order` INT NOT NULL,
  PRIMARY KEY (`category_id`, `product_id`),
  INDEX `fk_category_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_category_has_product_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_category_has_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`ek_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_category_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_currency_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_currency_lang` (
  `currency_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  INDEX `fk_currency_lang_currency1_idx` (`currency_id` ASC),
  INDEX `fk_currency_lang_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_currency_lang_currency1`
    FOREIGN KEY (`currency_id`)
    REFERENCES `mydb`.`ek_currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_currency_lang_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_condition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(64) NOT NULL,
  `combinator` VARCHAR(12) NOT NULL,
  `negation` TINYINT(1) NOT NULL,
  `start_group` TINYINT(1) NOT NULL,
  `end_group` TINYINT(1) NOT NULL,
  `left_operand` VARCHAR(64) NOT NULL,
  `operator` VARCHAR(64) NOT NULL,
  `right_operand` VARCHAR(64) NOT NULL,
  `right_operand2` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_action` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source` VARCHAR(64) NOT NULL,
  `source2` VARCHAR(64) NULL,
  `operator` VARCHAR(64) NOT NULL,
  `target` VARCHAR(64) NOT NULL,
  `target2` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_carrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_carrier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_currency_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_currency_shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `currency_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_currency_shop_currency1_idx` (`currency_id` ASC),
  INDEX `fk_currency_shop_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_currency_shop_currency1`
    FOREIGN KEY (`currency_id`)
    REFERENCES `mydb`.`ek_currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_currency_shop_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_carrier_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_carrier_lang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `description` TEXT NOT NULL,
  `carrier_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carrier_lang_carrier1_idx` (`carrier_id` ASC),
  INDEX `fk_carrier_lang_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_carrier_lang_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `mydb`.`ek_carrier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_lang_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_carrier_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_carrier_shop` (
  `carrier_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  INDEX `fk_carrier_shop_carrier1_idx` (`carrier_id` ASC),
  INDEX `fk_carrier_shop_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_carrier_shop_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `mydb`.`ek_carrier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_shop_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_carrier_has_condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_carrier_has_condition` (
  `carrier_id` INT NOT NULL,
  `condition_id` INT NOT NULL,
  PRIMARY KEY (`carrier_id`, `condition_id`),
  INDEX `fk_carrier_has_condition_condition1_idx` (`condition_id` ASC),
  INDEX `fk_carrier_has_condition_carrier1_idx` (`carrier_id` ASC),
  CONSTRAINT `fk_carrier_has_condition_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `mydb`.`ek_carrier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_has_condition_condition1`
    FOREIGN KEY (`condition_id`)
    REFERENCES `mydb`.`ek_condition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_carrier_has_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_carrier_has_action` (
  `carrier_id` INT NOT NULL,
  `action_id` INT NOT NULL,
  PRIMARY KEY (`carrier_id`, `action_id`),
  INDEX `fk_carrier_has_action_action1_idx` (`action_id` ASC),
  INDEX `fk_carrier_has_action_carrier1_idx` (`carrier_id` ASC),
  CONSTRAINT `fk_carrier_has_action_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `mydb`.`ek_carrier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_has_action_action1`
    FOREIGN KEY (`action_id`)
    REFERENCES `mydb`.`ek_action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_tag_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_has_tag` (
  `product_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `tag_id`),
  INDEX `fk_product_has_tag_tag1_idx` (`tag_id` ASC),
  INDEX `fk_product_has_tag_product1_idx` (`product_id` ASC),
  INDEX `fk_product_has_tag_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_product_has_tag_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`ek_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`ek_tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_tag_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_discount_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_discount_rule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(64) NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_discount_rule_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_discount_rule_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_discount_rule_has_condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_discount_rule_has_condition` (
  `discount_rule_id` INT NOT NULL,
  `condition_id` INT NOT NULL,
  PRIMARY KEY (`discount_rule_id`, `condition_id`),
  INDEX `fk_discount_rule_has_condition_condition1_idx` (`condition_id` ASC),
  INDEX `fk_discount_rule_has_condition_discount_rule1_idx` (`discount_rule_id` ASC),
  CONSTRAINT `fk_discount_rule_has_condition_discount_rule1`
    FOREIGN KEY (`discount_rule_id`)
    REFERENCES `mydb`.`ek_discount_rule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discount_rule_has_condition_condition1`
    FOREIGN KEY (`condition_id`)
    REFERENCES `mydb`.`ek_condition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_discount_rule_has_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_discount_rule_has_action` (
  `discount_rule_id` INT NOT NULL,
  `action_id` INT NOT NULL,
  PRIMARY KEY (`discount_rule_id`, `action_id`),
  INDEX `fk_discount_rule_has_action_action1_idx` (`action_id` ASC),
  INDEX `fk_discount_rule_has_action_discount_rule1_idx` (`discount_rule_id` ASC),
  CONSTRAINT `fk_discount_rule_has_action_discount_rule1`
    FOREIGN KEY (`discount_rule_id`)
    REFERENCES `mydb`.`ek_discount_rule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discount_rule_has_action_action1`
    FOREIGN KEY (`action_id`)
    REFERENCES `mydb`.`ek_action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_discount_rule_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_discount_rule_lang` (
  `discount_rule_id` INT NOT NULL,
  `label` INT NOT NULL,
  `lang_id` INT NOT NULL,
  INDEX `fk_discount_rule_lang_discount_rule1_idx` (`discount_rule_id` ASC),
  INDEX `fk_discount_rule_lang_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_discount_rule_lang_discount_rule1`
    FOREIGN KEY (`discount_rule_id`)
    REFERENCES `mydb`.`ek_discount_rule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discount_rule_lang_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_lang` (
  `product_id` INT NOT NULL,
  `label` VARCHAR(256) NOT NULL,
  `description` TEXT NOT NULL,
  `shop_id` INT NOT NULL,
  INDEX `fk_product_lang_product1_idx` (`product_id` ASC),
  INDEX `fk_product_lang_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_product_lang_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`ek_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_lang_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_reference_shop_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_reference_shop_lang` (
  `product_reference_shop_id` INT NOT NULL,
  `label` VARCHAR(256) NULL,
  `description` TEXT NULL,
  INDEX `fk_product_reference_shop_lang_product_reference_shop1_idx` (`product_reference_shop_id` ASC),
  CONSTRAINT `fk_product_reference_shop_lang_product_reference_shop1`
    FOREIGN KEY (`product_reference_shop_id`)
    REFERENCES `mydb`.`ek_product_reference_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  `text` TEXT NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user1_idx` (`user_id` ASC),
  INDEX `fk_comment_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`ek_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_has_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_has_comment` (
  `product_id` INT NOT NULL,
  `comment_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `comment_id`),
  INDEX `fk_product_has_comment_comment1_idx` (`comment_id` ASC),
  INDEX `fk_product_has_comment_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_has_comment_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`ek_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_comment_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `mydb`.`ek_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_feature` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(128) NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feature_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_feature_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_feature_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_feature_value` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(512) NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feature_value_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_feature_value_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_has_feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_has_feature` (
  `product_id` INT NOT NULL,
  `feature_id` INT NOT NULL,
  `feature_value_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `feature_id`),
  INDEX `fk_product_has_feature_feature1_idx` (`feature_id` ASC),
  INDEX `fk_product_has_feature_product1_idx` (`product_id` ASC),
  INDEX `fk_product_has_feature_feature_value1_idx` (`feature_value_id` ASC),
  CONSTRAINT `fk_product_has_feature_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_has_feature_feature1`
    FOREIGN KEY (`feature_id`)
    REFERENCES `mydb`.`ek_feature` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_has_feature_feature_value1`
    FOREIGN KEY (`feature_value_id`)
    REFERENCES `mydb`.`ek_feature_value` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_shop_configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_shop_configuration` (
  `shop_id` INT NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `value` VARCHAR(256) NOT NULL,
  INDEX `fk_shop_configuration_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_shop_configuration_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_origin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_origin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(64) NOT NULL,
  `value` VARCHAR(128) NOT NULL,
  `image` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_product_has_product_origin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_product_has_product_origin` (
  `product_id` INT NOT NULL,
  `product_origin_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `product_origin_id`),
  INDEX `fk_product_has_product_origin_product_origin1_idx` (`product_origin_id` ASC),
  INDEX `fk_product_has_product_origin_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_has_product_origin_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_has_product_origin_product_origin1`
    FOREIGN KEY (`product_origin_id`)
    REFERENCES `mydb`.`ek_product_origin` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_payment_method` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_mode_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_payment_mode_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_payment_method_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_payment_method_shop` (
  `payment_method_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  INDEX `fk_payment_method_shop_payment_method1_idx` (`payment_method_id` ASC),
  INDEX `fk_payment_method_shop_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_payment_method_shop_payment_method1`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `mydb`.`ek_payment_method` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_method_shop_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_order_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_status_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_order_status_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `mydb`.`ek_lang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_order_status_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_order_status_shop` (
  `order_status_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  `color` VARCHAR(24) NOT NULL,
  INDEX `fk_order_status_shop_order_status1_idx` (`order_status_id` ASC),
  INDEX `fk_order_status_shop_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_order_status_shop_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `mydb`.`ek_order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_status_shop_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`ek_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `reference` VARCHAR(64) NOT NULL,
  `date` DATETIME NOT NULL,
  `tracking_number` VARCHAR(64) NULL,
  `user_info` TEXT NOT NULL,
  `shop_info` TEXT NOT NULL,
  `invoice_address` TEXT NOT NULL,
  `billing_address` TEXT NOT NULL,
  `order_details` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`ek_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ek_order_has_order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ek_order_has_order_status` (
  `order_id` INT NOT NULL,
  `order_status_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`order_id`, `order_status_id`),
  INDEX `fk_order_has_order_status_order_status1_idx` (`order_status_id` ASC),
  INDEX `fk_order_has_order_status_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_has_order_status_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`ek_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_order_status_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `mydb`.`ek_order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
