<?php




$prc = "AutoAdmin.zilu.csv_fournisseurs_comparatif";
include __DIR__ . "/../../../NullosAdmin/inc/common.php";


$profile = array_replace_recursive($profile, [
    'model' => [
        'headers' => [
            'id',
            'ref_hldp',
            'ref_lf',
            'produit',
            'm3',
            'gw',
            'nw',
            'vendu_par',
            'ean',
            'nom_hldp',
            'nom_leaderfit',
            'poids',
            'materiaux',
            'etat_import',
            'largeur',
            'hauteur',
            'longueur',
            'resistance',
            'autres',
            'MOQ',
            'packaging',
            'categorie',
            'descriptif',
            'url',
            'en_products',
            'en_sold_by',
            'en_packaging',
            'en_material',
            'en_description',
            'en_category',
            'es_products',
            'es_sold_by',
            'es_packaging',
            'es_material',
            'es_category',
            'moyenne',
            'wohlstand',
            'rising',
            'top_asia',
            'azuni',
            'kylin',
            'modern_sports',
            'gyco',
            'lion',
            'live_up',
            'ironmaster',
            'record',
            'tengtai',
            'dekai',
            'alex',
            'regal',
            'helisports',
            'amaya',
            'msd',
            'fournisseur',
            'unit',
            'pa_dollar',
            'pa_fdp_inclus',
            'ob_marge_hldp',
            'ob_pv_fob_dollar',
            'ob_pv_fob',
            'ob_pv_hldp_dollar',
            'ob_pv_hldp',
            'pv_lf_orange',
            'reduction',
            'produit_specifique',
            'rev_marge_hldp',
            'rev_pv_fob_dollar',
            'rev_pv_fob',
            'rev_pv_hldp_dollar',
            'rev_pv_hldp',
            'gev_marge_hldp',
            'gev_pv_fob_dollar',
            'gev_pv_fob',
            'gev_pv_hldp_dollar',
            'gev_pv_hldp',
            'gev_pv_hldp2',
            'gev_pv_hldp3',
            'cha_marge_hldp',
            'cha_pv_fob_dollar',
            'cha_pv_fob',
            'cha_pv_hldp_dollar',
            'cha_pv_hldp',
            'cha_pv_hldp2',
            'kin_marge_hldp',
            'kin_pv_fob_dollar',
            'kin_pv_fob',
            'kin_pv_hldp_dollar',
            'kin_pv_hldp',
            'kin_pv_hldp2',
            'fit_marge_hldp',
            'fit_pv_fob_dollar',
            'fit_pv_fob',
            'fit_pv_hldp_dollar',
            'fit_pv_hldp',
            'fit_pv_hldp2',
            'lf_pv_public',
            'lf_pv_public_dollar',
            'lf_reduction',
            'lf_pv_revendeur',
            'lf_pv_revendeur_dollar',
            'action',
        ],
        'ric' => [
            'id',
        ],
        'actionButtons' => [
            'addItem' => [
                'label' => 'Add Csv_fournisseurs_comparatif',
            ],
        ],
    ],
]);
